Use readFileFromWorkspace instead of streamFileFromWorkspace
ERROR: (dsl.groovy, line 1) No signature of method: groovy.lang.GroovyShell.evaluate() is applicable for argument types: (java.io.FileInputStream) values: [java.io.FileInputStream@620b5050]
Possible solutions: evaluate(groovy.lang.GroovyCodeSource), evaluate(java.io.File), evaluate(java.io.Reader), evaluate(java.lang.String), evaluate(java.net.URI), evaluate(java.io.Reader, java.lang.String)