Try being explicit about loading on the "master" node
[Pipeline] load
Required context class hudson.FilePath is missing
Perhaps you forgot to surround the code with a step that provides this, such as: node
...
org.jenkinsci.plugins.workflow.steps.MissingContextVariableException: Required context class hudson.FilePath is missing